import { randomUUID } from 'node:crypto'
import { expect, test, type Locator, type Page } from '@playwright/test'
import type { MockRoute, MockScenario, PreviewMockRequest } from '../src/api/contracts/mocks'
import { authenticate, controlAPI, environmentHeader, environmentPath } from './helpers'
import { readE2EState } from './state'

test('reloads and leaves unsaved mock routes without a native confirmation', async ({ page }) => {
  const fixture = await createScenario('navigation', [route('lookup', '/saved', '{"saved":true}')])
  const nativeDialogs: string[] = []
  page.on('dialog', async (dialog) => {
    nativeDialogs.push(dialog.type())
    // Let a regression finish navigation so the assertion reports the unwanted prompt.
    await dialog.accept()
  })
  try {
    const saved = await controlAPI<MockScenario>(fixture.scenarioBase)
    await authenticate(page, `${fixture.path}&route=lookup`)
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    await editor.getByLabel('PATH', { exact: true }).click()
    await editor.getByLabel('PATH', { exact: true }).fill('/unsaved-edit')
    await expect(editor).toContainText('Unsaved changes')
    await page.reload()
    await expect(editor.getByLabel('PATH', { exact: true })).toHaveValue('/saved')
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    await expect(editor.getByText('All changes saved', { exact: true })).toHaveCount(0)
    expect(nativeDialogs).toEqual([])

    await page.getByRole('button', { name: 'ADD ROUTE', exact: true }).click()
    const newRoute = page.getByRole('region', { name: 'Create Route', exact: true })
    await newRoute.getByLabel('PATH', { exact: true }).click()
    await newRoute.getByLabel('PATH', { exact: true }).fill('/unsaved-new-route')
    await expect(newRoute).toContainText('Unsaved changes')
    const overviewURL = new URL(environmentPath(), readE2EState().baseURL).href
    await page.goto(overviewURL)
    await expect(page).toHaveURL(overviewURL)
    await expect(environmentHeader(page).getByRole('heading', { name: 'Overview', exact: true })).toBeVisible()
    expect(nativeDialogs).toEqual([])
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(saved)
  } finally {
    await fixture.cleanup()
  }
})

test('shows the save footer only for route edits in Routes and Preview', async ({ page }, testInfo) => {
  const fixture = await createScenario('footer', [route('lookup', '/saved', '{"saved":true}')])
  try {
    await authenticate(page, fixture.path + '&route=lookup')
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    const footer = editor.locator('.mock-workspace-footer')
    const layout = editor.locator('.mock-route-layout')
    const path = editor.getByLabel('PATH', { exact: true })
    await expect(footer).toHaveCount(0)
    const cleanHeight = (await layout.boundingBox())!.height
    await editor.getByRole('button', { name: 'Query parameters', exact: true }).click()
    await expect(footer).toHaveCount(0)
    await path.fill('/edited')
    await expect(footer).toBeInViewport()
    await expect(footer.getByRole('button', { name: 'SAVE ROUTE', exact: true })).toBeEnabled()
    expect((await layout.boundingBox())!.height).toBeLessThan(cleanHeight - 40)
    await path.fill('/saved')
    await expect(footer).toHaveCount(0)
    await expect.poll(async () => (await layout.boundingBox())!.height).toBeCloseTo(cleanHeight, 0)

    await editor.getByRole('tab', { name: 'Response', exact: true }).click()
    const body = editor.getByLabel('RESPONSE BODY', { exact: true })
    await body.fill('{"discard":true}')
    await footer.getByRole('button', { name: 'Discard route changes' }).click()
    await expect(body).toHaveValue('{"saved":true}')
    await expect(footer).toHaveCount(0)

    const preview = await openPreview(page)
    await preview.getByLabel('PREVIEW PATH', { exact: true }).fill('/sample-only')
    await preview.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(preview.getByRole('region', { name: 'Preview response' })).toContainText('501')
    await expect(footer).toHaveCount(0)
    await preview.getByRole('button', { name: 'RESET', exact: true }).click()
    await expect(footer).toHaveCount(0)
    await body.fill('{"saved":false}')
    await expect(footer).toBeInViewport()
    await page.screenshot({ path: testInfo.outputPath('mock-preview-unsaved-footer.png'), animations: 'disabled' })
    await footer.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(footer).toHaveCount(0)
    expect((await controlAPI<MockScenario>(fixture.scenarioBase)).routes[0].body).toBe('{"saved":false}')
    await body.fill('{"revert":true}')
    await expect(footer).toBeInViewport()
    await body.fill('{"saved":false}')
    await expect(footer).toHaveCount(0)
    await page.screenshot({ path: testInfo.outputPath('mock-preview-saved-no-footer.png'), animations: 'disabled' })
    await openRoutes(page)
    await expect(footer).toHaveCount(0)
  } finally {
    await fixture.cleanup()
  }
})

test('switches Routes and Preview while retaining the selected route, configuration, draft, and result', async ({ page }) => {
  const fixture = await createScenario('workspace', [route('lookup', '/inventory', '{"available":true}'), route('other', '/other', 'other')])
  try {
    await authenticate(page, fixture.path + '&route=lookup')
    const saved = await controlAPI<MockScenario>(fixture.scenarioBase)
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    const views = page.getByRole('tablist', { name: 'Mock workspace view' })
    const routeTitle = page.locator('.mock-route-heading h2')
    const endpoint = page.locator('.mock-route-heading__endpoint')
    const routesTab = views.getByRole('tab', { name: 'Routes', exact: true })
    const previewTab = views.getByRole('tab', { name: 'Preview', exact: true })
    const browser = page.locator('.mock-route-browser')
    const configuration = editor.locator('.mock-route-configuration')
    const preview = page.getByRole('form', { name: 'Mock request preview' })
    const queryToggle = editor.getByRole('button', { name: 'Query parameters', exact: true })
    const query = editor.getByRole('table', { name: 'Query parameters', exact: true })
    const path = editor.getByLabel('PATH', { exact: true })
    const samplePath = preview.getByLabel('PREVIEW PATH', { exact: true })
    const response = preview.getByRole('region', { name: 'Preview response', exact: true })
    const responseTab = editor.getByRole('tab', { name: 'Response', exact: true })
    await expect(routesTab).toHaveAttribute('aria-selected', 'true')
    await expect(browser).toBeVisible()
    await expect(preview).toBeHidden()
    await expect(routeTitle).toHaveText('lookup')
    await expect(endpoint.locator('.mock-route-method')).toHaveText('GET')
    await expect(endpoint.locator('code')).toHaveText('/inventory')
    const listingLeft = (await browser.boundingBox())!.x
    const editorRight = await editor.evaluate((element) => element.getBoundingClientRect().right)
    await expect(queryToggle).toHaveAttribute('aria-expanded', 'false')
    await expect(queryToggle).toHaveText('QUERY PARAMETERS0')
    await editor.getByRole('button', { name: 'Add query parameter', exact: true }).click()
    await expect(query.getByLabel('New query parameter name', { exact: true })).toBeFocused()
    await addQueryParameter(query, 'warehouse', 'central')
    await expect(queryToggle).toHaveText('QUERY PARAMETERS1')
    await queryToggle.press('Space')
    await expect(query).toBeHidden()
    await responseTab.click()
    await editor.getByLabel('RESPONSE BODY', { exact: true }).fill('{"available":false}')

    await routesTab.focus()
    await routesTab.press('ArrowRight')
    await expect(previewTab).toBeFocused()
    await expect(previewTab).toHaveAttribute('aria-selected', 'true')
    await expect(browser).toBeHidden()
    await expect(preview).toBeVisible()
    await expect(responseTab).toHaveAttribute('aria-selected', 'true')
    await expect(page.locator('.mock-route-heading h2')).toHaveText('lookup')
    const configurationBox = (await configuration.boundingBox())!
    const previewBox = (await preview.boundingBox())!
    expect(configurationBox.x).toBeCloseTo(listingLeft, 0)
    expect(configurationBox.x + configurationBox.width).toBeCloseTo(previewBox.x, 0)
    expect(previewBox.x + previewBox.width).toBeCloseTo(editorRight, 0)
    expect(configurationBox.y).toBeCloseTo(previewBox.y, 0)
    expect(configurationBox.height).toBeCloseTo(previewBox.height, 0)
    await expect(editor.getByRole('button', { name: 'SAVE ROUTE', exact: true })).toHaveCount(1)
    await expect(samplePath).toHaveValue('/inventory')
    await preview.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('Matched lookup')
    await expect(response.getByRole('tabpanel')).toContainText('"available": false')
    await response.getByRole('tab', { name: 'Headers', exact: true }).click()

    await previewTab.focus()
    await previewTab.press('Home')
    await expect(routesTab).toBeFocused()
    await expect(browser).toBeVisible()
    await expect(preview).toBeHidden()
    await expect(page.getByRole('button', { name: 'Edit lookup route', exact: true })).toHaveAttribute('aria-current', 'true')
    await expect(responseTab).toHaveAttribute('aria-selected', 'true')
    await expect(editor.getByLabel('RESPONSE BODY', { exact: true })).toHaveValue('{"available":false}')
    await editor.getByRole('tab', { name: 'Request', exact: true }).click()
    await expect(queryToggle).toHaveAttribute('aria-expanded', 'false')
    await queryToggle.press('Enter')
    await expect(query.getByLabel('Query parameter value 1', { exact: true })).toHaveValue('central')
    await path.fill('/changed')
    await expect(endpoint.locator('code')).toHaveText('/changed')
    await routesTab.focus()
    await routesTab.press('End')
    await expect(previewTab).toBeFocused()
    await expect(editor.getByRole('tab', { name: 'Request', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(samplePath).toHaveValue('/inventory')
    await expect(routeTitle).toHaveText('lookup')
    await expect(endpoint.locator('code')).toHaveText('/changed')
    await expect(response).toContainText('Matched lookup')
    await expect(response.getByRole('tab', { name: 'Headers', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(preview.getByRole('status')).toHaveText('OUTDATED')
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(saved)
    await preview.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('No route matched')
    await preview.getByRole('button', { name: 'RESET', exact: true }).click()
    await expect(samplePath).toHaveValue('/changed')
    await preview.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('Matched lookup')
    await expect(preview.getByRole('status')).toBeEmpty()

    await query.getByLabel('Query parameter value 1', { exact: true }).fill('')
    await queryToggle.click()
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText('choose Exists')
    await expect(queryToggle).toHaveAttribute('aria-expanded', 'true')
    await query.getByLabel('Query parameter value 1', { exact: true }).fill('central')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    expect((await controlAPI<MockScenario>(fixture.scenarioBase)).routes[0]).toMatchObject({ path: '/changed', body: '{"available":false}', query: { warehouse: { match: 'equals', value: 'central' } } })
    await previewTab.focus()
    await previewTab.press('ArrowLeft')
    await expect(routesTab).toBeFocused()
    await expect(page.getByRole('button', { name: 'Edit lookup route', exact: true })).toHaveAttribute('aria-current', 'true')
    await page.reload()
    await expect(routesTab).toHaveAttribute('aria-selected', 'true')
    await expect(path).toHaveValue('/changed')
  } finally {
    await fixture.cleanup()
  }
})

test('opens a route from its Preview menu action with retained drafts and keyboard focus', async ({ page }, testInfo) => {
  const fixture = await createScenario('menu', [route('lookup', '/inventory', '{"available":true}'), route('other', '/other', '{"other":true}')])
  try {
    await authenticate(page, `${fixture.path}&route=lookup`)
    const saved = await controlAPI<MockScenario>(fixture.scenarioBase)
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    const previewTab = page.getByRole('tablist', { name: 'Mock workspace view' }).getByRole('tab', { name: 'Preview', exact: true })
    const preview = page.getByRole('form', { name: 'Mock request preview' })
    let previewRequests = 0
    page.on('request', (request) => {
      if (request.method() === 'POST' && request.url().endsWith(`${fixture.scenarioBase}/preview`)) previewRequests++
    })
    await editor.getByLabel('PATH', { exact: true }).fill('/draft-lookup')
    await page.getByRole('button', { name: 'Route actions for other', exact: true }).click()
    const otherMenu = page.getByRole('menu', { name: 'other route actions', exact: true })
    await expect(otherMenu.getByRole('menuitem')).toHaveText(['EDIT', 'PREVIEW', 'DELETE'])
    for (const action of await otherMenu.getByRole('menuitem').all()) await expect(action).toBeInViewport({ ratio: 1 })
    await expect(editor.getByLabel('ROUTE NAME', { exact: true })).toHaveValue('lookup')
    await page.screenshot({ path: testInfo.outputPath('mock-route-preview-menu.png'), animations: 'disabled' })
    await otherMenu.getByRole('menuitem', { name: 'PREVIEW', exact: true }).click()
    await expect(page).toHaveURL(/route=other$/)
    await expect(previewTab).toHaveAttribute('aria-selected', 'true')
    await expect(previewTab).toBeFocused()
    await expect(page.locator('.mock-route-browser')).toBeHidden()
    await expect(page.getByRole('menu', { name: 'other route actions', includeHidden: true })).toHaveCount(0)
    await expect(editor.getByLabel('ROUTE NAME', { exact: true })).toHaveValue('other')
    await expect(page.locator('.mock-route-heading h2')).toHaveText('other')
    await expect(page.locator('.mock-route-heading__endpoint code')).toHaveText('/other')
    await expect(preview.getByLabel('PREVIEW PATH', { exact: true })).toHaveValue('/other')
    expect(previewRequests).toBe(0)

    await openRoutes(page)
    const lookupActions = page.getByRole('button', { name: 'Route actions for lookup', exact: true })
    await lookupActions.focus()
    await lookupActions.press('Enter')
    await page.keyboard.press('Tab')
    await expect(page.getByRole('menuitem', { name: 'EDIT', exact: true })).toBeFocused()
    await page.keyboard.press('Tab')
    const previewAction = page.getByRole('menuitem', { name: 'PREVIEW', exact: true })
    await expect(previewAction).toBeFocused()
    await previewAction.press('Enter')
    await expect(page).toHaveURL(/route=lookup$/)
    await expect(previewTab).toBeFocused()
    await expect(editor.getByLabel('PATH', { exact: true })).toHaveValue('/draft-lookup')
    await expect(page.locator('.mock-route-heading h2')).toHaveText('lookup')
    await expect(page.locator('.mock-route-heading__endpoint code')).toHaveText('/draft-lookup')
    await expect(preview.getByLabel('PREVIEW PATH', { exact: true })).toHaveValue('/draft-lookup')
    await expect(editor.getByRole('button', { name: 'SAVE ROUTE', exact: true })).toBeEnabled()
    expect(previewRequests).toBe(0)
    await preview.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    const response = preview.getByRole('region', { name: 'Preview response', exact: true })
    await expect(response).toContainText('Matched lookup')
    await response.getByRole('tab', { name: 'Headers', exact: true }).click()
    await editor.getByRole('tab', { name: 'Response', exact: true }).click()
    await openRoutes(page)
    await lookupActions.click()
    await previewAction.click()
    await expect(previewTab).toBeFocused()
    await expect(editor.getByRole('tab', { name: 'Response', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(response).toContainText('Matched lookup')
    await expect(response.getByRole('tab', { name: 'Headers', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(preview.getByLabel('PREVIEW PATH', { exact: true })).toHaveValue('/draft-lookup')
    expect(previewRequests).toBe(1)
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(saved)
    await openRoutes(page)
    await page.getByRole('button', { name: 'Route actions for other', exact: true }).click()
    await otherMenu.getByRole('menuitem', { name: 'EDIT', exact: true }).click()
    await expect(editor.getByLabel('ROUTE NAME', { exact: true })).toHaveValue('other')
    await expect(page.locator('.mock-route-browser')).toBeVisible()
    await expect(preview).toBeHidden()
  } finally {
    await fixture.cleanup()
  }
})

test('keeps Routes and Preview usable in both themes and narrow workspaces', async ({ page }, testInfo) => {
  const name = 'lookup-inventory-availability-for-checkout-and-fulfillment'
  const path = '/inventory/{sku}/warehouses/{warehouse}/availability'
  const fixture = await createScenario('workspace-with-a-long-scenario-name', [route(name, path, '{"available":false,"quantity":0}')])
  try {
    await authenticate(page, fixture.path + '&route=' + name)
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    const header = page.locator('.mock-scenario-header')
    const routeTitle = header.getByRole('heading', { name, exact: true })
    const assertHeaderFits = async () => {
      await expect(routeTitle).toBeInViewport()
      await expect(routeTitle).toHaveAttribute('title', name)
      await expect(header.locator('.mock-route-heading__endpoint code')).toHaveText(path)
      await expect(header.locator('.mock-scenario-toggle')).toBeInViewport({ ratio: 1 })
      await expect(header.getByRole('switch')).toBeEnabled()
      const context = (await header.locator('.mock-scenario-header__context').boundingBox())!
      const main = (await header.locator('.mock-scenario-header__route').boundingBox())!
      const identity = (await header.locator('.mock-route-heading').boundingBox())!
      const endpoint = (await header.locator('.mock-route-heading__endpoint').boundingBox())!
      const tabs = (await header.getByRole('tablist').boundingBox())!
      expect(context.y + context.height).toBeLessThanOrEqual(main.y)
      expect(identity.x + identity.width).toBeLessThanOrEqual(tabs.x)
      expect(endpoint.x + endpoint.width).toBeLessThanOrEqual(identity.x + identity.width + 1)
      expect(tabs.x + tabs.width).toBeLessThanOrEqual(main.x + main.width + 1)
    }
    for (const theme of ['dark', 'light'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
      await openRoutes(page)
      await expect(page.locator('.mock-route-browser')).toBeVisible()
      await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
      await assertHeaderFits()
      await page.screenshot({ path: testInfo.outputPath('mock-workspace-routes-' + theme + '.png'), animations: 'disabled' })
      const preview = await openPreview(page)
      await preview.getByRole('button', { name: 'PREVIEW', exact: true }).click()
      await assertPreviewFits(page)
      await assertHeaderFits()
      await page.screenshot({ path: testInfo.outputPath('mock-workspace-preview-request-' + theme + '.png'), animations: 'disabled' })
      await editor.getByRole('tab', { name: 'Response', exact: true }).click()
      await expect(editor.getByLabel('RESPONSE BODY', { exact: true })).toBeInViewport()
      await page.screenshot({ path: testInfo.outputPath('mock-workspace-preview-response-' + theme + '.png'), animations: 'disabled' })
      await editor.getByRole('tab', { name: 'Request', exact: true }).click()
    }
    for (const width of [760, 540]) {
      await page.setViewportSize({ width, height: 820 })
      await assertPreviewFits(page)
      await assertHeaderFits()
      await expect(page.locator('.mock-route-browser')).toBeHidden()
      await page.screenshot({ path: testInfo.outputPath('mock-workspace-preview-' + width + '.png'), animations: 'disabled' })
      await openRoutes(page)
      await expect(page.locator('.mock-route-browser')).toBeVisible()
      await expect(editor.getByRole('tablist', { name: 'Mock route configuration' })).toBeInViewport()
      await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
      await assertHeaderFits()
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
      await page.screenshot({ path: testInfo.outputPath('mock-workspace-routes-' + width + '.png'), animations: 'disabled' })
      await openPreview(page)
    }
  } finally {
    await fixture.cleanup()
  }
})

test('renames a route with its draft, previews the new name, and follows the saved selection', async ({ page }) => {
  const original = route('lookup', '/inventory/{sku}', '{"phase":"saved"}', {
    query: { warehouse: { match: 'regex', value: 'central|east' } },
    headers: { 'Content-Type': 'application/json', 'X-Custom': 'preserved' }, status: 202, delayMs: 10,
  })
  const fixture = await createScenario('rename', [original, route('peer', '/health', 'healthy')])
  try {
    await authenticate(page, `${fixture.path}&route=lookup`)
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    const name = editor.getByLabel('ROUTE NAME', { exact: true })
    const routeTitle = page.locator('.mock-route-heading h2')
    await expect(name).toBeEnabled()
    const before = await controlAPI<MockScenario>(fixture.scenarioBase)
    await name.fill('renamed')
    await expect(routeTitle).toHaveText('renamed')
    await editor.getByRole('tab', { name: 'Response', exact: true }).click()
    await editor.getByLabel('RESPONSE BODY', { exact: true }).fill('{"phase":"renamed"}')
    await page.getByRole('button', { name: 'Edit peer route', exact: true }).click()
    await expect(name).toHaveValue('peer')
    await expect(routeTitle).toHaveText('peer')
    await page.getByRole('button', { name: 'Edit lookup route', exact: true }).click()
    await expect(name).toHaveValue('renamed')
    await expect(routeTitle).toHaveText('renamed')
    await name.fill('peer')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText('Route name peer is duplicated')
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(before)
    await name.fill('renamed')
    const preview = await openPreview(page)
    await expect(routeTitle).toHaveText('renamed')
    await preview.getByLabel('Query parameter value 1', { exact: true }).fill('central')
    const previewRequest = page.waitForRequest((request) => request.method() === 'POST' && request.url().endsWith('/preview'))
    await preview.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    expect((await previewRequest).postDataJSON()).toMatchObject({ originalRoute: 'lookup', draft: { name: 'renamed', body: '{"phase":"renamed"}' } })
    await expect(editor.getByRole('region', { name: 'Preview response' })).toContainText('Matched renamed')
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(before)
    const saveRequest = page.waitForRequest((request) => request.method() === 'PUT' && request.url().endsWith('/routes/lookup'))
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    expect((await saveRequest).postDataJSON()).toMatchObject({ ...original, name: 'renamed', body: '{"phase":"renamed"}' })
    await expect(page).toHaveURL(/route=renamed$/)
    await expect(page.getByRole('button', { name: 'Edit lookup route', exact: true })).toHaveCount(0)
    await expect(page.getByRole('tab', { name: 'Preview', exact: true })).toHaveAttribute('aria-selected', 'true')
    await openRoutes(page)
    await expect(page.getByRole('button', { name: 'Edit renamed route', exact: true })).toBeVisible()
    await expect(name).toHaveValue('renamed')
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    const saved = await controlAPI<MockScenario>(fixture.scenarioBase)
    expect(saved.routes).toHaveLength(2)
    expect(saved.routes.find((route) => route.name === 'renamed')).toMatchObject({ ...original, name: 'renamed', body: '{"phase":"renamed"}', createdAt: before.routes.find((route) => route.name === 'lookup')!.createdAt })
    expect(saved.routes.find((route) => route.name === 'peer')).toEqual(before.routes.find((route) => route.name === 'peer'))
    await page.reload()
    await expect(name).toHaveValue('renamed')
    await expect(editor.getByLabel('PATH', { exact: true })).toHaveValue('/inventory/{sku}')
    await expect(editor.getByRole('table', { name: 'Query parameters', exact: true }).getByLabel('Query parameter match 1', { exact: true })).toHaveValue('regex')

    await name.fill('renamed-again')
    await editor.getByRole('tab', { name: 'Response', exact: true }).click()
    await expect(editor.getByLabel('RESPONSE BODY', { exact: true })).toHaveValue('{"phase":"renamed"}')
    const secondSave = page.waitForRequest((request) => request.method() === 'PUT' && request.url().endsWith('/routes/renamed'))
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    expect((await secondSave).postDataJSON().name).toBe('renamed-again')
    await expect(page).toHaveURL(/route=renamed-again$/)
    await expect(name).toHaveValue('renamed-again')
    await name.fill('discard-this-name')
    await expect(routeTitle).toHaveText('discard-this-name')
    await editor.getByRole('button', { name: 'Discard route changes', exact: true }).click()
    await expect(name).toHaveValue('renamed-again')
    await expect(routeTitle).toHaveText('renamed-again')
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    await page.getByRole('button', { name: /^Back to mock scenarios from / }).click()
    await expect(page).toHaveURL(/\?tab=mocks$/)
    await expect(page.getByRole('dialog')).toHaveCount(0)
  } finally {
    await fixture.cleanup()
  }
})

test('configures path and query matching with compact selectors', async ({ page }, testInfo) => {
  const fixture = await createScenario('match-controls', [route('lookup', '/inventory', '{"available":true}', { query: { coupon: { match: 'exists' } } })])
  try {
    await authenticate(page, `${fixture.path}&route=lookup`)
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    const pathMatch = editor.getByLabel('Path match', { exact: true })
    const path = editor.getByLabel('PATH', { exact: true })
    const query = await openRequiredQuery(editor)
    const couponMatch = query.getByLabel('Query parameter match 1', { exact: true })
    const couponValue = query.getByLabel('Query parameter value 1', { exact: true })
    await expect(pathMatch).toHaveValue('exact')
    await expect(couponMatch).toHaveValue('exists')
    await expect(couponValue).toBeDisabled()
    await expect(couponValue).toHaveAttribute('placeholder', 'Any value')
    await expect(editor.getByText('An empty value matches any value.', { exact: true })).toHaveCount(0)

    await pathMatch.selectOption('template')
    await expect(path).toHaveValue('/inventory')
    await expect(path).toHaveAttribute('placeholder', '/inventory/{sku}')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText('needs a path parameter')
    await path.fill('/inventory/{sku}')
    await couponMatch.selectOption('equals')
    await expect(couponValue).toBeEnabled()
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText('choose Exists')
    await couponValue.fill('summer')
    await couponMatch.selectOption('exists')
    await expect(couponValue).toBeDisabled()
    await couponMatch.selectOption('equals')
    await expect(couponValue).toHaveValue('summer')
    await couponMatch.selectOption('exists')

    const requestForm = await openPreview(page)
    await expect(requestForm.getByLabel('PREVIEW PATH', { exact: true })).toHaveValue('/inventory/sku-123')
    await expect(requestForm.getByLabel('Query parameter value 1', { exact: true })).toHaveValue('')
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Preview response' })).toContainText('Matched lookup')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    expect((await controlAPI<MockScenario>(fixture.scenarioBase)).routes[0]).toMatchObject({ path: '/inventory/{sku}', query: { coupon: { match: 'exists' } } })
    await page.reload()
    await expect(pathMatch).toHaveValue('template')
    await expect(couponMatch).toHaveValue('exists')

    for (const theme of ['light', 'dark'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
      await page.screenshot({ path: testInfo.outputPath(`mock-match-controls-${theme}.png`), animations: 'disabled' })
    }
    await page.setViewportSize({ width: 760, height: 800 })
    await expect(pathMatch).toBeInViewport()
    await expect(couponMatch).toBeInViewport()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(760)
    await expect.poll(() => editor.evaluate((element) => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
    await page.screenshot({ path: testInfo.outputPath('mock-match-controls-narrow.png'), animations: 'disabled' })

    await pathMatch.selectOption('exact')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText('Choose Template')
    await path.fill('/inventory/coffee-mug')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    await page.reload()
    await expect(pathMatch).toHaveValue('exact')
    await path.fill('/inventory/{sku}')
    await expect(pathMatch).toHaveValue('template')
  } finally {
    await fixture.cleanup()
  }
})

test('edits, previews, validates, and saves regex query matchers', async ({ page }, testInfo) => {
  const fixture = await createScenario('query-regex', [route('lookup', '/inventory', '{"available":true}')])
  try {
    await authenticate(page, `${fixture.path}&route=lookup`)
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    const query = await openRequiredQuery(editor)
    const match = query.getByLabel('Query parameter match 1', { exact: true })
    const value = query.getByLabel('Query parameter value 1', { exact: true })
    await query.getByLabel('New query parameter name', { exact: true }).fill('sku')
    await match.selectOption('regex')
    await match.focus()
    await page.keyboard.press('Tab')
    await expect(value).toBeFocused()
    await value.fill('[')
    const before = await controlAPI<MockScenario>(fixture.scenarioBase)
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText('query parameter sku has an invalid regex')
    await expect(value).toHaveValue('[')
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(before)

    const preview = await openPreview(page)
    await preview.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(preview.getByRole('alert')).toContainText('invalid regex')
    await expect(preview.getByRole('alert')).toBeInViewport()
    const pattern = 'coffee-(mug|beans)'
    await value.fill(pattern)
    await match.selectOption('exists')
    await expect(value).toBeDisabled()
    await match.selectOption('regex')
    await expect(value).toHaveValue(pattern)

    await preview.getByRole('button', { name: 'RESET', exact: true }).click()
    const sample = preview.getByLabel('Query parameter value 1', { exact: true })
    await expect(sample).toHaveValue('')
    await expect(preview.getByLabel('Query parameter match 1', { exact: true })).toHaveCount(0)
    const response = editor.getByRole('region', { name: 'Preview response' })
    await sample.fill('coffee-mug')
    await preview.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('Matched lookup')
    await sample.fill('iced-coffee-mug')
    await preview.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('No route matched')
    await addQueryParameter(preview.getByRole('table', { name: 'Preview query parameters', exact: true }), 'sku', 'coffee-beans')
    await preview.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('Matched lookup')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    expect((await controlAPI<MockScenario>(fixture.scenarioBase)).routes[0].query).toEqual({ sku: { match: 'regex', value: pattern } })
    await page.reload()
    await expect(match).toHaveValue('regex')
    await expect(value).toHaveValue(pattern)
    for (const theme of ['light', 'dark'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
      await page.screenshot({ path: testInfo.outputPath(`mock-query-regex-${theme}.png`), animations: 'disabled' })
    }
    await page.setViewportSize({ width: 760, height: 800 })
    await expect(match).toBeInViewport()
    await expect(value).toBeInViewport()
    await expect.poll(() => editor.evaluate((element) => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
    await page.screenshot({ path: testInfo.outputPath('mock-query-regex-narrow.png'), animations: 'disabled' })

    await match.selectOption('equals')
    await expect(value).toHaveValue(pattern)
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    expect((await controlAPI<MockScenario>(fixture.scenarioBase)).routes[0].query).toEqual({ sku: { match: 'equals', value: pattern } })
    await match.selectOption('exists')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    await page.reload()
    await expect(match).toHaveValue('exists')
    await expect(value).toBeDisabled()
    expect((await controlAPI<MockScenario>(fixture.scenarioBase)).routes[0].query).toEqual({ sku: { match: 'exists' } })
  } finally {
    await fixture.cleanup()
  }
})

test('previews a new unsaved route in a disabled scenario without changing saved or runtime state', async ({ page }) => {
  const fixture = await createScenario('new')
  try {
    await authenticate(page, fixture.path)
    await expect(page.getByRole('tab', { name: 'Preview', exact: true })).toBeDisabled()
    await page.getByRole('button', { name: 'ADD ROUTE', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Preview', exact: true })).toBeEnabled()
    const editor = page.getByRole('region', { name: 'Create Route', exact: true })
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    await openPreview(page)
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    await openRoutes(page)
    await editor.getByLabel('SERVICE', { exact: true }).selectOption('inventory')
    await editor.getByLabel('PATH', { exact: true }).fill('/inventory/{sku}')
    await expect(editor.locator('.mock-workspace-footer')).toBeVisible()
    await expect(editor.getByRole('button', { name: 'Cancel new route', exact: true })).toBeEnabled()
    await editor.getByLabel('ROUTE NAME', { exact: true }).fill('lookup')
    await addQueryParameter(await openRequiredQuery(editor), 'warehouse', 'central')
    await editor.getByRole('tab', { name: 'Response', exact: true }).click()
    await editor.getByLabel('RESPONSE STATUS').selectOption('503')
    await editor.getByLabel('RESPONSE BODY').fill('{"available":false,"message":"<script>preview</script>"}')
    await editor.getByLabel('DELAY (MS)', { exact: true }).fill('25')
    const headerTable = await openResponseHeaders(editor)
    await expect(headerTable.getByLabel('Header name 1', { exact: true })).toHaveValue('Content-Type')
    await expect(headerTable.getByLabel('Header value 1', { exact: true })).toHaveValue('application/json')
    await headerTable.getByLabel('New header name', { exact: true }).fill('X-Preview')
    await headerTable.getByLabel('Header value 2', { exact: true }).fill('unsaved')

    const before = await readPreviewSideEffects(fixture.base, fixture.scenarioBase)
    const requestForm = await openPreview(page)
    await expect(requestForm).toBeVisible()
    await expect(requestForm.getByLabel('PREVIEW SERVICE', { exact: true })).toHaveValue('inventory')
    await expect(requestForm.getByLabel('PREVIEW METHOD', { exact: true })).toHaveValue('GET')
    await expect(requestForm.getByLabel('PREVIEW PATH', { exact: true })).toHaveValue(/^\/inventory\/[^{}]+$/)
    const queryTable = requestForm.getByRole('table', { name: 'Preview query parameters', exact: true })
    await expect(queryTable.getByLabel('Query parameter name 1', { exact: true })).toHaveValue('warehouse')
    await expect(queryTable.getByLabel('Query parameter value 1', { exact: true })).toHaveValue('central')
    await queryTable.getByRole('button', { name: 'Remove query parameter 1', exact: true }).click()
    await expect(queryTable).toBeVisible()
    await expect(queryTable.getByLabel('New query parameter name', { exact: true })).toBeFocused()
    await requestForm.getByLabel('PREVIEW PATH', { exact: true }).fill('/inventory/coffee-mug')
    await addQueryParameter(queryTable, 'warehouse', 'central')
    await addQueryParameter(queryTable, 'tag', 'one')
    await addQueryParameter(queryTable, 'tag', 'two')
    await addQueryParameter(queryTable, 'empty', '')
    const submitted = page.waitForRequest((request) => request.method() === 'POST' && request.url().endsWith(`${fixture.scenarioBase}/preview`))
    await requestForm.getByLabel('PREVIEW PATH', { exact: true }).press('Enter')
    const envelope = (await submitted).postDataJSON() as PreviewMockRequest
    expect(envelope).toMatchObject({
      request: { service: 'inventory', method: 'GET', path: '/inventory/coffee-mug', query: { warehouse: ['central'], tag: ['one', 'two'], empty: [''] } },
      draft: { name: 'lookup', service: 'inventory', status: 503, enabled: true },
    })
    expect(envelope).not.toHaveProperty('originalRoute')

    const response = page.getByRole('region', { name: 'Preview response' })
    await expect(response).toContainText('Matched lookup')
    await expect(response).toContainText('503')
    await expect(response).toContainText('25 ms')
    await expect(response.getByRole('tab', { name: 'Body', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(response.getByRole('tabpanel')).toContainText('"available": false')
    await expect(response.getByRole('tabpanel')).toContainText('<script>preview</script>')
    await expect(response.locator('script')).toHaveCount(0)
    await response.getByRole('button', { name: 'Raw', exact: true }).click()
    await expect(response.getByRole('tabpanel')).toHaveText('{"available":false,"message":"<script>preview</script>"}')
    await response.getByRole('button', { name: 'Formatted', exact: true }).click()
    await response.getByRole('tab', { name: 'Headers', exact: true }).click()
    await expect(response.getByRole('tabpanel')).toContainText('X-Preview')
    await expect(response.getByRole('tabpanel')).toContainText('unsaved')
    await expect(response.getByRole('tabpanel')).toContainText('application/json')
    expect(await readPreviewSideEffects(fixture.base, fixture.scenarioBase)).toEqual(before)

    await expect(editor.getByLabel('RESPONSE BODY')).toHaveValue('{"available":false,"message":"<script>preview</script>"}')
    await expect(editor.getByLabel('DELAY (MS)', { exact: true })).toHaveValue('25')
    await expect(requestForm.getByLabel('PREVIEW PATH', { exact: true })).toHaveValue('/inventory/coffee-mug')
    await expect(response).toContainText('Matched lookup')
    await expect(editor.getByText('OUTDATED', { exact: true })).toHaveCount(0)
  } finally {
    await fixture.cleanup()
  }
})

test('keeps request and response configuration in accessible tabs and saves the complete draft from either tab', async ({ page }, testInfo) => {
  const fixture = await createScenario('tabs', [route('lookup', '/original', '{"saved":true}')])
  try {
    await authenticate(page, `${fixture.path}&route=lookup`)
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    const tabs = editor.getByRole('tablist', { name: 'Mock route configuration', exact: true })
    const requestTab = tabs.getByRole('tab', { name: 'Request', exact: true })
    const responseTab = tabs.getByRole('tab', { name: 'Response', exact: true })
    await expect(requestTab).toHaveAttribute('aria-selected', 'true')
    await expect(responseTab).toHaveAttribute('aria-selected', 'false')
    await expect(editor.getByRole('tabpanel')).toHaveCount(1)
    await expect(editor.getByRole('tabpanel', { name: 'Request', exact: true })).toBeVisible()
    await expect(editor.getByLabel('RESPONSE BODY')).toHaveCount(0)
    await expect(editor.getByLabel('ROUTE ENABLED', { exact: true })).toHaveCount(0)
    await editor.getByLabel('PATH', { exact: true }).fill('/changed')
    const required = await openRequiredQuery(editor)
    await addQueryParameter(required, 'warehouse', 'central')

    await requestTab.focus()
    await page.keyboard.press('ArrowRight')
    await expect(responseTab).toBeFocused()
    await expect(responseTab).toHaveAttribute('aria-selected', 'true')
    await expect(editor.getByRole('tabpanel')).toHaveCount(1)
    await expect(editor.getByRole('tabpanel', { name: 'Response', exact: true })).toBeVisible()
    await expect(editor.getByLabel('PATH', { exact: true })).toHaveCount(0)
    await expect(required).toHaveCount(0)
    await expect(editor.getByLabel('ROUTE ENABLED', { exact: true })).toHaveCount(0)
    await editor.getByLabel('RESPONSE STATUS').selectOption('201')
    await editor.getByLabel('DELAY (MS)', { exact: true }).fill('12')
    await editor.getByLabel('RESPONSE BODY').fill('{"phase":1}')
    const headers = editor.getByRole('table', { name: 'Response headers', exact: true })
    await headers.getByLabel('New header name', { exact: true }).fill('X-Phase')
    await headers.getByLabel('Header value 2', { exact: true }).fill('one')
    await responseTab.focus()
    await page.keyboard.press('Home')
    await expect(requestTab).toBeFocused()
    await expect(requestTab).toHaveAttribute('aria-selected', 'true')
    await expect(editor.getByLabel('PATH', { exact: true })).toHaveValue('/changed')
    await expect(required.getByLabel('Query parameter value 1', { exact: true })).toHaveValue('central')
    await page.keyboard.press('End')
    await expect(responseTab).toBeFocused()
    await expect(editor.getByLabel('RESPONSE BODY')).toHaveValue('{"phase":1}')
    await expect(editor.getByLabel('DELAY (MS)', { exact: true })).toHaveValue('12')
    await expect(headers.getByLabel('Header value 2', { exact: true })).toHaveValue('one')
    await page.keyboard.press('ArrowLeft')
    await expect(requestTab).toBeFocused()
    await page.keyboard.press('ArrowRight')
    await expect(responseTab).toBeFocused()

    await openPreview(page)
    await page.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    const response = page.getByRole('region', { name: 'Preview response' })
    await expect(response).toContainText('Matched lookup')
    await expect(response).toContainText('201')
    await expect(response).toContainText('12 ms')
    await expect(responseTab).toHaveAttribute('aria-selected', 'true')
    await expect(editor.getByLabel('RESPONSE BODY')).toHaveValue('{"phase":1}')
    await requestTab.click()
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    let saved = await controlAPI<MockScenario>(fixture.scenarioBase)
    expect(saved.routes[0]).toMatchObject({ name: 'lookup', method: 'GET', path: '/changed', query: { warehouse: { match: 'equals', value: 'central' } }, status: 201, delayMs: 12, body: '{"phase":1}', headers: { 'Content-Type': 'application/json', 'X-Phase': 'one' } })

    await editor.getByLabel('METHOD', { exact: true }).selectOption('POST')
    await editor.getByLabel('PATH', { exact: true }).fill('/changed-again')
    await responseTab.click()
    await editor.getByLabel('RESPONSE BODY').fill('{"phase":2}')
    await editor.getByLabel('RESPONSE STATUS').selectOption('202')
    await headers.getByLabel('Header value 2', { exact: true }).fill('two')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    saved = await controlAPI<MockScenario>(fixture.scenarioBase)
    expect(saved.routes[0]).toMatchObject({ name: 'lookup', method: 'POST', path: '/changed-again', query: { warehouse: { match: 'equals', value: 'central' } }, status: 202, delayMs: 12, body: '{"phase":2}', headers: { 'Content-Type': 'application/json', 'X-Phase': 'two' } })

    for (const theme of ['light', 'dark'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
      for (const tab of ['Request', 'Response'] as const) {
        await tabs.getByRole('tab', { name: tab, exact: true }).click()
        await expect(editor.getByRole('tabpanel', { name: tab, exact: true })).toBeVisible()
        await expect(tabs).toBeInViewport()
        await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
        await page.screenshot({ path: testInfo.outputPath(`mock-config-${tab.toLowerCase()}-${theme}.png`), animations: 'disabled' })
      }
    }
    await page.setViewportSize({ width: 760, height: 800 })
    for (const tab of ['Request', 'Response'] as const) {
      await tabs.getByRole('tab', { name: tab, exact: true }).click()
      await editor.getByRole('table', { name: tab === 'Request' ? 'Query parameters' : 'Response headers', exact: true }).scrollIntoViewIfNeeded()
      await expect(tabs).toBeInViewport()
      await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(760)
      await page.screenshot({ path: testInfo.outputPath(`mock-config-${tab.toLowerCase()}-narrow.png`), animations: 'disabled' })
    }
  } finally {
    await fixture.cleanup()
  }
})

test('edits required and preview query rows while preserving matching, repeated values, and request reset', async ({ page }, testInfo) => {
  const fixture = await createScenario('query', [
    route('lookup', '/query', '{"query":true}', { query: { warehouse: { match: 'equals', value: 'central' } } }),
    route('other', '/other', '{"other":true}'),
  ])
  try {
    const saved = await controlAPI<MockScenario>(fixture.scenarioBase)
    await authenticate(page, `${fixture.path}&route=lookup`)
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    const required = await openRequiredQuery(editor)
    await expect(required.getByLabel('Query parameter name 1', { exact: true })).toHaveValue('warehouse')
    await expect(required.getByLabel('Query parameter value 1', { exact: true })).toHaveValue('central')
    await required.getByLabel('Query parameter value 1', { exact: true }).fill('east=zone')
    await required.getByLabel('New query parameter name', { exact: true }).pressSequentially('include')
    await expect(required.getByLabel('Query parameter name 2', { exact: true })).toHaveValue('include')
    await expect(required.getByLabel('Query parameter name 2', { exact: true })).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(required.getByLabel('Query parameter match 2', { exact: true })).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(required.getByLabel('Query parameter value 2', { exact: true })).toBeFocused()
    await required.getByLabel('Query parameter value 2', { exact: true }).fill('availability')
    await addQueryParameter(required, 'remove', 'temporary')
    await required.getByRole('button', { name: 'Remove query parameter 3', exact: true }).click()
    await expect(required.getByLabel('Query parameter name 3', { exact: true })).toHaveCount(0)
    await expect(required.getByLabel('New query parameter name', { exact: true })).toBeFocused()
    await page.getByRole('button', { name: 'Edit other route', exact: true }).click()
    await expect(editor.getByLabel('PATH', { exact: true })).toHaveValue('/other')
    await page.getByRole('button', { name: 'Edit lookup route', exact: true }).click()
    await expect(editor.getByLabel('PATH', { exact: true })).toHaveValue('/query')
    await openRequiredQuery(editor)
    await expect(required.getByLabel('Query parameter value 1', { exact: true })).toHaveValue('east=zone')
    await expect(required.getByLabel('Query parameter value 2', { exact: true })).toHaveValue('availability')
    for (const theme of ['light', 'dark'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
      await required.scrollIntoViewIfNeeded()
      await page.screenshot({ path: testInfo.outputPath(`mock-required-query-${theme}.png`), animations: 'disabled' })
    }
    const originalViewport = page.viewportSize()!
    await page.setViewportSize({ width: 760, height: 800 })
    await required.scrollIntoViewIfNeeded()
    await expect(required.getByLabel('Query parameter value 2', { exact: true })).toBeInViewport()
    await expect(required.getByRole('button', { name: 'Remove query parameter 2', exact: true })).toBeInViewport()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(760)
    await expect.poll(() => required.evaluate((element) => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
    await page.screenshot({ path: testInfo.outputPath('mock-required-query-narrow.png'), animations: 'disabled' })
    await page.setViewportSize(originalViewport)

    const requestForm = await openPreview(page)
    const query = requestForm.getByRole('table', { name: 'Preview query parameters', exact: true })
    await expect(query).toBeVisible()
    await expect(query.getByLabel('Query parameter name 1', { exact: true })).toHaveValue('warehouse')
    await expect(query.getByLabel('Query parameter value 1', { exact: true })).toHaveValue('east=zone')
    await expect(query.getByLabel('Query parameter name 2', { exact: true })).toHaveValue('include')
    await expect(query.getByLabel('Query parameter value 2', { exact: true })).toHaveValue('availability')
    await addQueryParameter(query, 'tag', 'one')
    await addQueryParameter(query, 'tag', 'two')
    await addQueryParameter(query, 'empty', '')
    const submitted = page.waitForRequest((request) => request.method() === 'POST' && request.url().endsWith(`${fixture.scenarioBase}/preview`))
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    expect((await submitted).postDataJSON()).toMatchObject({
      request: { query: { warehouse: ['east=zone'], include: ['availability'], tag: ['one', 'two'], empty: [''] } },
      draft: { query: { warehouse: { match: 'equals', value: 'east=zone' }, include: { match: 'equals', value: 'availability' } } },
    })
    const response = page.getByRole('region', { name: 'Preview response' })
    await expect(response).toContainText('Matched lookup')
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(saved)
    const outdated = editor.getByText('OUTDATED', { exact: true })
    await query.getByLabel('Query parameter value 2', { exact: true }).fill('pricing')
    await expect(outdated).toBeVisible()
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('No route matched')
    await expect(response).toContainText('501')
    await requestForm.getByRole('button', { name: 'RESET', exact: true }).click()
    await expect(query.getByLabel('Query parameter value 2', { exact: true })).toHaveValue('availability')
    await expect(query.getByLabel('Query parameter name 3', { exact: true })).toHaveCount(0)
    await expect(query.getByLabel('New query parameter name', { exact: true })).toHaveValue('')
    await expect(outdated).toBeVisible()
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('Matched lookup')
    await expect(outdated).toHaveCount(0)
    await query.getByLabel('New query parameter value', { exact: true }).fill('orphan')
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText(/query.*name|name.*query/i)
    await query.getByRole('button', { name: 'Remove query parameter 3', exact: true }).click()
    await expect(editor.getByRole('alert')).toHaveCount(0)
    await addQueryParameter(query, 'tag', 'one')
    await addQueryParameter(query, 'tag', 'two')
    await openRequiredQuery(editor)
    await expect(required.getByLabel('Query parameter name 3', { exact: true })).toHaveCount(0)
    await expect(query.getByLabel('Query parameter name 3', { exact: true })).toHaveValue('tag')
    await expect(query.getByLabel('Query parameter value 3', { exact: true })).toHaveValue('one')
    await expect(query.getByLabel('Query parameter name 4', { exact: true })).toHaveValue('tag')
    await expect(query.getByLabel('Query parameter value 4', { exact: true })).toHaveValue('two')
    for (const theme of ['light', 'dark'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
      await query.scrollIntoViewIfNeeded()
      await page.screenshot({ path: testInfo.outputPath(`mock-preview-query-${theme}.png`), animations: 'disabled' })
    }
    await page.setViewportSize({ width: 760, height: 800 })
    await query.scrollIntoViewIfNeeded()
    await expect(query.getByLabel('Query parameter value 4', { exact: true })).toBeInViewport()
    await expect(query.getByRole('button', { name: 'Remove query parameter 4', exact: true })).toBeInViewport()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(760)
    await expect.poll(() => query.evaluate((element) => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
    await page.screenshot({ path: testInfo.outputPath('mock-preview-query-narrow.png'), animations: 'disabled' })
    await page.setViewportSize(originalViewport)

    await openRequiredQuery(editor)
    await required.getByLabel('Query parameter name 2', { exact: true }).fill('warehouse')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText(/duplicat/i)
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(saved)
    await required.getByLabel('Query parameter name 2', { exact: true }).fill('')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText(/query.*name|name.*query/i)
    await required.getByLabel('Query parameter name 2', { exact: true }).fill('include')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    const updated = await controlAPI<MockScenario>(fixture.scenarioBase)
    expect(updated.routes.find(({ name }) => name === 'lookup')?.query).toEqual({ warehouse: { match: 'equals', value: 'east=zone' }, include: { match: 'equals', value: 'availability' } })
  } finally {
    await fixture.cleanup()
  }
})

test('collapses response headers, retains drafts, reveals validation errors, and saves exact values', async ({ page }, testInfo) => {
  const fixture = await createScenario('headers', [
    route('lookup', '/headers', '{"headers":true}'),
    route('other', '/other', '{"other":true}', { headers: {} }),
  ])
  try {
    const saved = await controlAPI<MockScenario>(fixture.scenarioBase)
    await authenticate(page, `${fixture.path}&route=lookup`)
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    const headers = await openResponseHeaders(editor)
    const headerToggle = editor.getByRole('button', { name: 'Response headers', exact: true })
    const responseTab = editor.getByRole('tab', { name: 'Response', exact: true })
    await expect(headerToggle).toHaveAttribute('aria-expanded', 'true')
    await expect(headerToggle).toHaveText('RESPONSE HEADERS1')
    await expect(headers.getByLabel('Header name 1', { exact: true })).toHaveValue('Content-Type')
    await headerToggle.press('Space')
    await expect(headers).toBeHidden()
    await editor.getByRole('tab', { name: 'Request', exact: true }).click()
    await responseTab.click()
    await expect(headerToggle).toHaveAttribute('aria-expanded', 'false')
    await headerToggle.press('Enter')
    await expect(headers.getByLabel('Header value 1', { exact: true })).toHaveValue('application/json')
    await headerToggle.click()
    await editor.getByRole('button', { name: 'Add response header', exact: true }).click()
    await expect(headers.getByLabel('New header name', { exact: true })).toBeFocused()
    await headers.getByLabel('New header name', { exact: true }).pressSequentially('X-Trace')
    await expect(headers.getByLabel('Header name 2', { exact: true })).toHaveValue('X-Trace')
    await expect(headers.getByLabel('Header name 2', { exact: true })).toBeFocused()
    await expect(headers.getByLabel('New header name', { exact: true })).toHaveValue('')
    await page.keyboard.press('Tab')
    await expect(headers.getByLabel('Header value 2', { exact: true })).toBeFocused()
    await headers.getByLabel('Header value 2', { exact: true }).fill('temporary')
    await headers.getByLabel('Header name 2', { exact: true }).fill('X-Location')
    await headers.getByLabel('Header value 2', { exact: true }).fill('https://example.com/region:central')
    await headers.getByLabel('New header name', { exact: true }).fill('X-Remove')
    await headers.getByLabel('Header value 3', { exact: true }).fill('remove-me')
    await headers.getByRole('button', { name: 'Remove header 3', exact: true }).click()
    await expect(headers.getByLabel('Header name 3', { exact: true })).toHaveCount(0)
    await expect(headers.getByLabel('New header name', { exact: true })).toHaveValue('')
    await expect(headers.getByLabel('New header name', { exact: true })).toBeFocused()
    await expect(headerToggle).toHaveText('RESPONSE HEADERS2')

    await page.getByRole('button', { name: 'Edit other route', exact: true }).click()
    await expect(editor.getByLabel('PATH', { exact: true })).toHaveValue('/other')
    await responseTab.click()
    await expect(headerToggle).toHaveAttribute('aria-expanded', 'false')
    await expect(headerToggle).toHaveText('RESPONSE HEADERS0')
    await expect(headers).toBeHidden()
    await page.getByRole('button', { name: 'Edit lookup route', exact: true }).click()
    await expect(editor.getByLabel('PATH', { exact: true })).toHaveValue('/headers')
    await openResponseHeaders(editor)
    await expect(headers.getByLabel('Header name 2', { exact: true })).toHaveValue('X-Location')
    await expect(headers.getByLabel('Header value 2', { exact: true })).toHaveValue('https://example.com/region:central')
    for (const theme of ['light', 'dark'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
      await headers.scrollIntoViewIfNeeded()
      await page.screenshot({ path: testInfo.outputPath(`mock-response-headers-${theme}.png`), animations: 'disabled' })
      await headerToggle.click()
      await expect(headers).toBeHidden()
      await headerToggle.scrollIntoViewIfNeeded()
      await page.screenshot({ path: testInfo.outputPath(`mock-response-headers-collapsed-${theme}.png`), animations: 'disabled' })
      await headerToggle.click()
    }
    const originalViewport = page.viewportSize()!
    await page.setViewportSize({ width: 760, height: 800 })
    await headers.scrollIntoViewIfNeeded()
    await expect(headers.getByLabel('Header value 2', { exact: true })).toBeInViewport()
    await expect(headers.getByRole('button', { name: 'Remove header 2', exact: true })).toBeInViewport()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(760)
    await expect.poll(() => headers.evaluate((element) => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
    await page.screenshot({ path: testInfo.outputPath('mock-response-headers-narrow.png'), animations: 'disabled' })
    await page.setViewportSize(originalViewport)

    await openPreview(page)
    await page.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    const response = page.getByRole('region', { name: 'Preview response' })
    await expect(response).toContainText('Matched lookup')
    await response.getByRole('tab', { name: 'Headers', exact: true }).click()
    await expect(response.getByRole('tabpanel')).toContainText('X-Location')
    await expect(response.getByRole('tabpanel')).toContainText('https://example.com/region:central')
    await expect(response.getByRole('tabpanel')).not.toContainText('X-Remove')
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(saved)

    await openResponseHeaders(editor)
    await expect(headers.getByLabel('Header value 2', { exact: true })).toHaveValue('https://example.com/region:central')
    await headers.getByLabel('Header name 2', { exact: true }).fill('content-type')
    await headerToggle.click()
    await editor.getByRole('tab', { name: 'Request', exact: true }).click()
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText(/duplicat/i)
    await expect(responseTab).toHaveAttribute('aria-selected', 'true')
    await expect(headerToggle).toHaveAttribute('aria-expanded', 'true')
    await expect(headers).toBeVisible()
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(saved)
    await headers.getByLabel('Header name 2', { exact: true }).fill('X-Location')
    await expect(editor.getByRole('alert')).toHaveCount(0)
    await headers.getByLabel('Header name 2', { exact: true }).fill('')
    await headerToggle.click()
    await editor.getByRole('tab', { name: 'Request', exact: true }).click()
    await openPreview(page)
    await page.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText(/header.*name|name.*header/i)
    await expect(responseTab).toHaveAttribute('aria-selected', 'true')
    await expect(headerToggle).toHaveAttribute('aria-expanded', 'true')
    await expect(headers).toBeVisible()

    await openResponseHeaders(editor)
    await expect(headers.getByLabel('Header value 2', { exact: true })).toHaveValue('https://example.com/region:central')
    await headers.getByLabel('Header name 2', { exact: true }).fill('X-Location')
    await openPreview(page)
    await page.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(editor.getByRole('alert')).toHaveCount(0)
    await expect(response).toContainText('Matched lookup')
    await editor.getByRole('button', { name: 'SAVE ROUTE', exact: true }).click()
    await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
    const updated = await controlAPI<MockScenario>(fixture.scenarioBase)
    expect(updated.routes.find(({ name }) => name === 'lookup')?.headers).toEqual({
      'Content-Type': 'application/json',
      'X-Location': 'https://example.com/region:central',
    })
    await page.reload()
    await openResponseHeaders(editor)
    await expect(headers.getByLabel('Header name 2', { exact: true })).toHaveValue('X-Location')
    await expect(headers.getByLabel('Header value 2', { exact: true })).toHaveValue('https://example.com/region:central')
    await expect(headers.getByLabel('New header name', { exact: true })).toHaveValue('')
    await expect(headers.getByLabel('New header value', { exact: true })).toHaveValue('')
  } finally {
    await fixture.cleanup()
  }
})

test('previews saved route overlays, precedence, no matches, disabled routes, and outdated results', async ({ page }, testInfo) => {
  const fixture = await createScenario('matching', [
    route('lookup', '/inventory/{sku}', '{"saved":true}'),
    route('special', '/inventory/special', '{"special":true}', { status: 202 }),
  ])
  try {
    const saved = await controlAPI<MockScenario>(fixture.scenarioBase)
    await authenticate(page, `${fixture.path}&route=lookup`)
    const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
    await editor.getByRole('tab', { name: 'Response', exact: true }).click()
    await editor.getByLabel('RESPONSE STATUS').selectOption('503')
    await editor.getByLabel('RESPONSE BODY').fill('{"draft":true}')
    const requestForm = await openPreview(page)
    await requestForm.getByLabel('PREVIEW PATH', { exact: true }).fill('/inventory/coffee-mug')
    const submitted = page.waitForRequest((request) => request.method() === 'POST' && request.url().endsWith(`${fixture.scenarioBase}/preview`))
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    expect((await submitted).postDataJSON()).toMatchObject({ originalRoute: 'lookup', draft: { name: 'lookup', body: '{"draft":true}', status: 503 } })
    const response = page.getByRole('region', { name: 'Preview response' })
    await expect(response).toContainText('Matched lookup')
    await expect(response).toContainText('503')
    await expect(response.getByRole('tabpanel')).toContainText('"draft": true')

    const outdated = editor.getByText('OUTDATED', { exact: true })
    await requestForm.getByLabel('PREVIEW PATH', { exact: true }).fill('/inventory/special')
    await expect(outdated).toBeVisible()
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('Matched special')
    await expect(response).toContainText('202')
    await expect(outdated).toHaveCount(0)
    await requestForm.getByLabel('PREVIEW METHOD', { exact: true }).selectOption('POST')
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('No route matched')
    await expect(response).toContainText('501')
    await expect(editor.getByRole('alert')).toHaveCount(0)

    await expect(editor.getByLabel('RESPONSE BODY')).toHaveValue('{"draft":true}')
    await editor.getByLabel('RESPONSE BODY').fill('{"draft":"updated"}')
    await expect(requestForm.getByLabel('PREVIEW METHOD', { exact: true })).toHaveValue('POST')
    await expect(requestForm.getByLabel('PREVIEW PATH', { exact: true })).toHaveValue('/inventory/special')
    await expect(outdated).toBeVisible()
    await requestForm.getByRole('button', { name: 'RESET', exact: true }).click()
    await expect(requestForm.getByLabel('PREVIEW METHOD', { exact: true })).toHaveValue('GET')
    await expect(requestForm.getByLabel('PREVIEW PATH', { exact: true })).toHaveValue(/^\/inventory\/[^{}]+$/)
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('Matched lookup')
    await expect(response.getByRole('tabpanel')).toContainText('"draft": "updated"')
    await expect(outdated).toHaveCount(0)
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(saved)

    await openRoutes(page)
    const routeEnabled = page.getByRole('switch', { name: 'lookup route enabled', exact: true })
    await routeEnabled.focus()
    await page.keyboard.press('Space')
    await expect(routeEnabled).not.toBeChecked()
    const routeRow = page.getByRole('listitem').filter({ has: routeEnabled })
    const disabledBadge = page.locator('.mock-route-heading .mock-route-disabled-state')
    await expect(routeRow.locator('.mock-route-disabled-state')).toHaveText('DISABLED')
    await expect(disabledBadge).toBeInViewport()
    await expect(editor.getByLabel('RESPONSE BODY', { exact: true })).toBeEnabled()
    for (const theme of ['dark', 'light'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
      await page.screenshot({ path: testInfo.outputPath('mock-disabled-route-' + theme + '.png'), animations: 'disabled' })
    }
    const disabled = await controlAPI<MockScenario>(fixture.scenarioBase)
    expect(disabled.routes.find((route) => route.name === 'lookup')).toMatchObject({ enabled: false, status: 200, body: '{"saved":true}' })
    await openPreview(page)
    await expect(disabledBadge).toBeInViewport()
    await expect(editor).toContainText('This route is disabled and will not match.')
    await expect(outdated).toBeVisible()
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('No route matched')
    await expect(response).toContainText('501')
    expect(await controlAPI<MockScenario>(fixture.scenarioBase)).toEqual(disabled)

    const changedRoute = route('special', '/inventory/special', '{"saved":"updated elsewhere"}', { status: 202 })
    await controlAPI(`${fixture.scenarioBase}/routes/special`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(changedRoute) })
    await expect(outdated).toBeVisible()
    await requestForm.getByLabel('PREVIEW PATH', { exact: true }).fill('/inventory/special')
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(response).toContainText('Matched special')
    await expect(response.getByRole('tabpanel')).toContainText('updated elsewhere')
    await expect(outdated).toHaveCount(0)
    for (const width of [760, 540]) {
      await page.setViewportSize({ width, height: 820 })
      await expect(disabledBadge).toBeInViewport()
      await expect(page.locator('.mock-route-heading h2')).toBeInViewport()
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
      await page.screenshot({ path: testInfo.outputPath('mock-disabled-preview-' + width + '.png'), animations: 'disabled' })
    }
  } finally {
    await fixture.cleanup()
  }
})

test('keeps preview validation errors local and recovers after correcting the draft and request', async ({ page }) => {
  const fixture = await createScenario('validation', [route('lookup', '/saved', '{"saved":true}')])
  try {
    await authenticate(page, fixture.path)
    await page.getByRole('button', { name: 'ADD ROUTE', exact: true }).click()
    const editor = page.getByRole('region', { name: 'Create Route', exact: true })
    await editor.getByLabel('SERVICE', { exact: true }).selectOption('inventory')
    await editor.getByLabel('PATH', { exact: true }).fill('/draft')
    await editor.getByLabel('ROUTE NAME', { exact: true }).fill('lookup')
    const requestForm = await openPreview(page)
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText(/already exists|duplicate/i)
    await expect(requestForm.getByRole('button', { name: 'PREVIEW', exact: true })).toBeEnabled()
    await expect(page.getByRole('region', { name: 'Preview response' }).getByRole('tabpanel')).toHaveCount(0)

    await editor.getByLabel('ROUTE NAME', { exact: true }).fill('new-route')
    let previewRequests = 0
    page.on('request', (request) => {
      if (request.method() === 'POST' && request.url().endsWith(`${fixture.scenarioBase}/preview`)) previewRequests++
    })
    await requestForm.getByLabel('PREVIEW PATH', { exact: true }).fill('https://example.com/draft')
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await expect(editor.getByRole('alert')).toBeVisible()
    expect(previewRequests).toBe(0)
    await requestForm.getByLabel('PREVIEW PATH', { exact: true }).fill('/draft')
    await requestForm.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    const response = page.getByRole('region', { name: 'Preview response' })
    await expect(response).toContainText('Matched new-route')
    await expect(editor.getByRole('alert')).toHaveCount(0)
    await expect(response.getByRole('tabpanel')).toContainText(/has no body/i)
    expect((await controlAPI<MockScenario>(fixture.scenarioBase)).routes.map(({ name }) => name)).toEqual(['lookup'])
  } finally {
    await fixture.cleanup()
  }
})

test('discards late preview results after switching routes and keeps the response pane usable across layouts', async ({ page }, testInfo) => {
  const fixture = await createScenario('pending', [
    route('first', '/first', '{"route":"first"}'),
    route('second', '/second', JSON.stringify({ route: 'second', lines: Array.from({ length: 100 }, (_, index) => `response line ${index}`) })),
  ])
  let releaseResponse = () => {}
  const responseReleased = new Promise<void>((resolve) => { releaseResponse = resolve })
  let finishIntercept = () => {}
  const interceptFinished = new Promise<void>((resolve) => { finishIntercept = resolve })
  let notifyFetched = () => {}
  const responseFetched = new Promise<void>((resolve) => { notifyFetched = resolve })
  const previewPattern = `**${fixture.scenarioBase}/preview`
  let interceptStarted = false
  let delayed = false
  try {
    await authenticate(page, `${fixture.path}&route=first`)
    await page.route(previewPattern, async (intercept) => {
      if (delayed) return await intercept.continue()
      delayed = true
      interceptStarted = true
      try {
        // Use the real matcher result; only delivery timing is controlled.
        const actual = await intercept.fetch()
        notifyFetched()
        await responseReleased
        await intercept.fulfill({ response: actual }).catch(() => {
          // Leaving a route aborts its request before the delayed result arrives.
        })
      } finally {
        finishIntercept()
      }
    })
    await openPreview(page)
    await page.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    await responseFetched
    await expect(page.getByRole('button', { name: 'RUNNING…', exact: true })).toBeDisabled()
    await page.getByLabel('PATH', { exact: true }).fill('/first-edited')
    await expect(page.getByRole('button', { name: 'PREVIEW', exact: true })).toBeEnabled()
    await openRoutes(page)
    await page.getByRole('button', { name: 'Edit second route', exact: true }).click()
    await openPreview(page)
    await page.getByRole('button', { name: 'PREVIEW', exact: true }).click()
    const response = page.getByRole('region', { name: 'Preview response' })
    await expect(response).toContainText('Matched second')
    releaseResponse()
    await interceptFinished
    await expect(response).toContainText('Matched second')
    await expect(response).not.toContainText('Matched first')
    await expect(page.getByLabel('PREVIEW PATH', { exact: true })).toHaveValue('/second')
    await expect(page.getByRole('button', { name: 'PREVIEW', exact: true })).toBeEnabled()

    await response.getByRole('tab', { name: 'Body', exact: true }).focus()
    await expect(response.getByRole('tab', { name: 'Body', exact: true })).toBeFocused()
    await page.keyboard.press('ArrowRight')
    await expect(response.getByRole('tab', { name: 'Headers', exact: true })).toBeFocused()
    await expect(response.getByRole('tab', { name: 'Headers', exact: true })).toHaveAttribute('aria-selected', 'true')
    await response.getByRole('tab', { name: 'Body', exact: true }).click()
    for (const theme of ['light', 'dark'] as const) {
      await page.emulateMedia({ colorScheme: theme })
      await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
      await assertPreviewFits(page)
      await page.screenshot({ path: testInfo.outputPath(`mock-preview-${theme}.png`), animations: 'disabled' })
    }
    await page.mouse.move(640, 350)
    await page.keyboard.press('Control+Shift+F')
    await expect(page.locator('.shell')).toHaveClass(/shell--focus-mode/)
    await assertPreviewFits(page)
    await page.screenshot({ path: testInfo.outputPath('mock-preview-focus.png'), animations: 'disabled' })
    await page.keyboard.press('Control+Shift+F')
    await page.setViewportSize({ width: 760, height: 800 })
    await assertPreviewFits(page)
    await page.screenshot({ path: testInfo.outputPath('mock-preview-narrow.png'), animations: 'disabled' })
  } finally {
    releaseResponse()
    if (interceptStarted) await interceptFinished
    await page.unroute(previewPattern)
    await fixture.cleanup()
  }
})

function route(name: string, path: string, body: string, overrides: Partial<MockRoute> = {}): MockRoute {
  return { name, service: 'inventory', method: 'GET', path, status: 200, body, headers: { 'Content-Type': 'application/json' }, enabled: true, ...overrides }
}

async function openPreview(page: Page) {
  await page.getByRole('tablist', { name: 'Mock workspace view' }).getByRole('tab', { name: 'Preview', exact: true }).click()
  const preview = page.getByRole('form', { name: 'Mock request preview' })
  await expect(preview).toBeVisible()
  return preview
}

async function openRoutes(page: Page) {
  await page.getByRole('tablist', { name: 'Mock workspace view' }).getByRole('tab', { name: 'Routes', exact: true }).click()
  await expect(page.locator('.mock-route-browser')).toBeVisible()
}

async function openResponseHeaders(editor: Locator) {
  await editor.getByRole('tab', { name: 'Response', exact: true }).click()
  const toggle = editor.getByRole('button', { name: 'Response headers', exact: true })
  if (await toggle.getAttribute('aria-expanded') === 'false') await toggle.click()
  const table = editor.getByRole('table', { name: 'Response headers', exact: true })
  await expect(table).toBeVisible()
  return table
}

async function openRequiredQuery(editor: Locator) {
  await editor.getByRole('tab', { name: 'Request', exact: true }).click()
  const toggle = editor.getByRole('button', { name: 'Query parameters', exact: true })
  if (await toggle.getAttribute('aria-expanded') === 'false') await toggle.click()
  const table = editor.getByRole('table', { name: 'Query parameters', exact: true })
  await expect(table).toBeVisible()
  return table
}

async function addQueryParameter(table: Locator, name: string, value: string) {
  const index = await table.getByLabel(/^Query parameter name \d+$/).count() + 1
  await table.getByLabel('New query parameter name', { exact: true }).fill(name)
  await table.getByLabel(`Query parameter value ${index}`, { exact: true }).fill(value)
}

async function createScenario(kind: string, routes: MockRoute[] = []) {
  const state = readE2EState()
  const base = `/api/v1/environments/${state.project}/${state.environment}`
  const name = `preview-${kind}-${randomUUID().slice(0, 8)}`
  const scenarioBase = `${base}/mocks/${name}`
  await controlAPI(`${base}/mocks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) })
  const cleanup = async () => { await controlAPI(scenarioBase, { method: 'DELETE' }) }
  try {
    for (const value of routes) {
      await controlAPI(`${scenarioBase}/routes/${value.name}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(value) })
    }
    return { base, scenarioBase, path: `${environmentPath('mocks')}&scenario=${name}`, cleanup }
  } catch (error) {
    await cleanup()
    throw error
  }
}

async function readPreviewSideEffects(base: string, scenarioBase: string) {
  type Snapshot = { services: Array<{ name: string; pid?: number; generation: number; status: string }>; bindings: unknown[] }
  const [scenario, snapshot, timeline, traffic, recordings] = await Promise.all([
    controlAPI<MockScenario>(scenarioBase),
    controlAPI<Snapshot>(base),
    controlAPI(`${base}/timeline?limit=1000`),
    controlAPI(`${base}/traffic/exchanges?protocol=http&limit=1000`),
    controlAPI(`${base}/recordings`),
  ])
  return { scenario, services: snapshot.services.map(({ name, pid, generation, status }) => ({ name, pid, generation, status })), bindings: snapshot.bindings, timeline, traffic, recordings }
}

async function assertPreviewFits(page: Page) {
  const editor = page.getByRole('region', { name: 'Edit Route', exact: true })
  const response = page.getByRole('region', { name: 'Preview response' })
  await expect(page.getByRole('form', { name: 'Mock request preview' })).toBeVisible()
  await expect(response).toBeVisible()
  await response.scrollIntoViewIfNeeded()
  await expect(response.getByRole('tabpanel')).toBeInViewport()
  await expect(editor.getByRole('tablist', { name: 'Mock route configuration' })).toBeInViewport()
  await expect(editor.getByRole('button', { name: 'PREVIEW', exact: true })).toBeInViewport()
  await expect(editor.locator('.mock-workspace-footer')).toHaveCount(0)
  await expect(page.getByRole('tablist', { name: 'Mock workspace view' })).toBeInViewport()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width)
  await expect.poll(() => editor.evaluate((element) => element.getBoundingClientRect().bottom)).toBeLessThanOrEqual(page.viewportSize()!.height + 1)
  await expect.poll(() => response.getByRole('tabpanel').evaluate((element) => element.getBoundingClientRect().height)).toBeGreaterThan(60)
}
