import { expect, test, type Locator } from '@playwright/test'
import { applicationRequest, authenticate, environmentPath } from './helpers'

test.describe.configure({ mode: 'serial' })

async function selectFirstTraceSpan(navigation: Locator) {
  await expect(navigation).toHaveAttribute('aria-busy', 'false')
  const firstSpan = navigation.getByRole('button', { name: 'First visible span in trace' })
  if (await firstSpan.isEnabled()) await firstSpan.click()
  await expect(navigation.locator('output')).toHaveAttribute('aria-label', /Span 1 of \d+/)
}

test('inspects captured request and response details in the exchange workbench', async ({ page }) => {
  await authenticate(page)
  const response = await applicationRequest('/checkout?sku=coffee-mug&quantity=2', {
    Authorization: 'Bearer browser-e2e-secret',
    'X-E2E-Trace': 'visible',
  })
  expect(response.status).toBe(200)

  await page.getByRole('navigation', { name: 'ui-e2e/local views' }).getByRole('button', { name: 'Traffic' }).click()
  await page.getByRole('tab', { name: 'EXCHANGES' }).click()
  const row = page.locator('button.traffic-row').filter({ hasText: '/checkout' }).filter({ hasText: 'external' }).first()
  await expect(row).toBeVisible()
  const exchangeDetailPattern = '**/api/v1/environments/**/traffic/exchanges/*'
  await page.route(exchangeDetailPattern, async (route) => {
    const response = await route.fetch()
    const exchange = await response.json() as Record<string, unknown>
    await route.fulfill({ response, json: { ...exchange, fault: 'ui-fault', recording: 'ui-recording', mockScenario: 'ui-mock', mockRoute: 'checkout' } })
  })
  await row.click()

  const detail = page.getByRole('dialog', { name: /Traffic request and response/ })
  await expect(detail).toContainText('GET /checkout')
  await page.unroute(exchangeDetailPattern)
  const viewport = page.viewportSize()
  const detailBox = await detail.boundingBox()
  expect(detailBox?.y).toBe(0)
  expect(detailBox?.height).toBe(viewport?.height)
  expect(detailBox?.width).toBe(900)
  expect((detailBox?.x ?? 0) + (detailBox?.width ?? 0)).toBe(viewport?.width)
  const detailScroll = await detail.locator('.traffic-detail__content').evaluate((element) => ({
    clientHeight: element.clientHeight,
    scrollHeight: element.scrollHeight,
  }))
  expect(detailScroll.scrollHeight - detailScroll.clientHeight).toBeLessThan(80)
  const overview = detail.getByRole('region', { name: 'Exchange overview' })
  await expect(overview.locator('.traffic-overview__heading')).toHaveText('OVERVIEW')
  await expect(overview.locator('.traffic-overview__panel')).toBeVisible()
  await expect(overview.locator('.traffic-overview__summary')).toHaveCount(0)
  await expect(overview.locator('.traffic-trace-context')).toHaveCount(0)
  await expect(overview.getByRole('list', { name: 'Exchange interventions' })).toHaveCount(0)
  const detailHeader = detail.locator('.traffic-detail__header')
  const interventions = detailHeader.getByRole('list', { name: 'Exchange interventions' })
  await expect(interventions).toHaveCSS('justify-content', 'flex-end')
  await expect(interventions.getByRole('listitem', { name: 'FAULT ui-fault' })).toHaveClass(/traffic-intervention-badge--fault/)
  await expect(interventions.getByRole('listitem', { name: 'RECORDING ui-recording' })).toHaveClass(/traffic-intervention-badge--recording/)
  await expect(interventions.getByRole('listitem', { name: 'MOCK ui-mock / checkout' })).toHaveClass(/traffic-intervention-badge--mock/)
  const interventionBox = await interventions.boundingBox()
  const overviewDataBox = await overview.locator('.traffic-overview__context').boundingBox()
  const detailHeaderBox = await detailHeader.boundingBox()
  expect((interventionBox?.y ?? 0) + (interventionBox?.height ?? 0)).toBeLessThanOrEqual((detailHeaderBox?.y ?? 0) + (detailHeaderBox?.height ?? 0))
  expect((interventionBox?.y ?? 0) + (interventionBox?.height ?? 0)).toBeLessThanOrEqual(overviewDataBox?.y ?? 0)
  const exchangeNavigation = detailHeader.getByRole('navigation', { name: 'Exchange navigation' })
  await expect(exchangeNavigation).toBeVisible()
  await expect(detailHeader.getByRole('navigation', { name: 'Trace span navigation' })).toHaveCount(0)
  await expect(exchangeNavigation.getByRole('button')).toHaveCount(2)
  const previousExchange = exchangeNavigation.getByRole('button', { name: 'Previous exchange' })
  const nextExchange = exchangeNavigation.getByRole('button', { name: 'Next exchange' })
  const exchangePosition = exchangeNavigation.locator('output')
  const initialPosition = await exchangePosition.getAttribute('aria-label')
  const positionMatch = initialPosition?.match(/^Exchange (\d+) of (\d+)$/)
  expect(positionMatch).not.toBeNull()
  const initialIndex = Number(positionMatch?.[1])
  const exchangeLength = Number(positionMatch?.[2])
  expect(initialIndex).toBeGreaterThanOrEqual(1)
  expect(initialIndex).toBeLessThan(exchangeLength)
  if (initialIndex === 1) await expect(previousExchange).toBeDisabled()
  else await expect(previousExchange).toBeEnabled()
  await expect(nextExchange).toBeEnabled()
  const initialDialogLabel = await detail.getAttribute('aria-label')
  await nextExchange.click()
  await expect(exchangePosition).toHaveAttribute('aria-label', `Exchange ${initialIndex + 1} of ${exchangeLength}`)
  await expect(detail).not.toHaveAttribute('aria-label', initialDialogLabel || '')
  await expect(previousExchange).toBeEnabled()
  await previousExchange.click()
  await expect(exchangePosition).toHaveAttribute('aria-label', `Exchange ${initialIndex} of ${exchangeLength}`)
  await expect(detail).toHaveAttribute('aria-label', initialDialogLabel || '')
  await expect(overview.locator('.traffic-overview__context > div').first()).toHaveCSS('padding-bottom', '14px')
  await expect(overview).toContainText('ENVIRONMENT')
  await expect(overview).toContainText('TARGET BINDING')
  await expect(overview.locator('.traffic-overview__context > div').filter({ hasText: 'STARTED' }).locator('strong')).toHaveText(/\d{1,2}:\d{2}:\d{2}\.\d{3}/)
  await expect(overview).not.toContainText('TARGET PROVIDER')
  await expect(overview).toContainText(/· local/)
  await expect(detail.getByRole('tab', { name: 'OVERVIEW' })).toHaveCount(0)
  const requestTab = detail.getByRole('tab', { name: /^REQUEST/ })
  await expect(requestTab).toHaveAttribute('aria-selected', 'true')
  await expect(requestTab).toHaveCSS('font-size', '10px')
  await expect.poll(async () => requestTab.evaluate((element) => getComputedStyle(element).fontSize === getComputedStyle(document.querySelector('.tabs button') as HTMLElement).fontSize)).toBe(true)
  const request = detail.locator('.traffic-message-workbench--request')
  await expect(request.locator('.traffic-message-workbench__summary')).not.toContainText(/captured|transferred/i)
  await expect(request.locator('.traffic-message-workbench__summary')).not.toContainText('content type not reported')
  await expect(request.getByRole('tab', { name: 'HEADERS', exact: true })).toHaveAttribute('aria-selected', 'true')
  const headerKey = request.locator('.traffic-headers__key').first()
  const headerValue = request.locator('.traffic-headers__value').first()
  await expect(headerKey).toBeVisible()
  await expect(headerValue).toBeVisible()
  await expect.poll(() => headerKey.evaluate((element) => getComputedStyle(element).color === getComputedStyle(element.parentElement as HTMLElement).color)).toBe(true)
  await expect.poll(async () => {
    const [keyColor, valueColor] = await Promise.all([
      headerKey.evaluate((element) => getComputedStyle(element).color),
      headerValue.evaluate((element) => getComputedStyle(element).color),
    ])
    return valueColor !== keyColor
  }).toBe(true)
  await expect(request).toContainText('Authorization: [REDACTED]')
  await expect(request).not.toContainText('Bearer browser-e2e-secret')
  await expect(request).toContainText(/X-E2E-Trace: visible/i)
  await expect(request).not.toContainText(/Traceparent:/i)
  await request.getByRole('tab', { name: 'RAW' }).click()
  await expect(request).toContainText('GET /checkout')
  await expect(request).toContainText('Authorization: [REDACTED]')

  await detail.getByRole('tab', { name: /^RESPONSE/ }).click()
  const capturedResponse = detail.locator('.traffic-message-workbench--response')
  await expect(capturedResponse.locator('.traffic-message-workbench__summary')).not.toContainText('captured')
  await expect(capturedResponse.getByRole('tab', { name: 'BODY' })).toHaveAttribute('aria-selected', 'true')
  await expect(capturedResponse).toContainText('"checkout": "accepted"')
  await expect(capturedResponse.locator('pre.traffic-json')).toBeVisible()
  const jsonKey = capturedResponse.locator('.traffic-json__key').first()
  await expect(jsonKey).toBeVisible()
  await expect.poll(() => jsonKey.evaluate((element) => getComputedStyle(element).color === getComputedStyle(element.parentElement as HTMLElement).color)).toBe(true)
  await expect(capturedResponse.locator('.traffic-json__string').first()).toBeVisible()
  await expect(capturedResponse.locator('.traffic-json__number').first()).toBeVisible()

  await detail.getByRole('button', { name: 'Full screen traffic details' }).click()
  await expect(detail).toHaveClass(/traffic-detail--maximized/)
  await expect(overview).toBeVisible()
  await expect(overview.locator('.traffic-overview__heading')).toHaveText('OVERVIEW')
  await expect(overview).toContainText('TARGET BINDING')
  await expect(detail.getByRole('tab', { name: 'COMPARE' })).toHaveAttribute('aria-selected', 'true')
  await expect(detail.locator('.traffic-message-workbench--request')).toBeVisible()
  await expect(detail.locator('.traffic-message-workbench--response')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(detail).not.toHaveClass(/traffic-detail--maximized/)
  await expect(overview).toBeVisible()
  await expect(detail.getByRole('tab', { name: 'COMPARE' })).toHaveCount(0)
  await expect(detail.getByRole('tab', { name: /^REQUEST/ })).toHaveAttribute('aria-selected', 'true')

  await detail.getByRole('button', { name: 'Close traffic details' }).click()
  const downstreamRow = page.locator('button.traffic-row').filter({ hasText: 'checkout→' }).first()
  await expect(downstreamRow).toBeVisible()
  await downstreamRow.click()
  const downstreamDetail = page.getByRole('dialog', { name: /Traffic request and response/ })
  const downstreamOverview = downstreamDetail.getByRole('region', { name: 'Exchange overview' })
  await expect(downstreamOverview.locator('.traffic-trace-context')).toHaveCount(0)
  const downstreamRequest = downstreamDetail.locator('.traffic-message-workbench--request')
  await downstreamRequest.getByRole('tab', { name: 'HEADERS', exact: true }).click()
  await expect(downstreamRequest).not.toContainText(/Traceparent:|\bB3:|X-B3-Trace-Id:|X-Datadog-Trace-Id:/i)
})

test('keeps short trace payloads pinned and preserves compare while navigating', async ({ page }) => {
  await authenticate(page)
  const response = await applicationRequest(`/checkout?sku=coffee-mug&quantity=1&layout=${Date.now()}`)
  expect(response.status).toBe(200)

  await page.getByRole('navigation', { name: 'ui-e2e/local views' }).getByRole('button', { name: 'Traffic' }).click()
  const row = page.locator('button.trace-row').filter({ hasText: '/checkout' }).first()
  await expect(row).toBeVisible()
  await row.click()
  await page.getByRole('region', { name: 'Trace waterfall' }).getByRole('button', { name: /Inspect external to checkout GET \/checkout/ }).click()

  const detail = page.getByRole('dialog', { name: /Traffic request and response/ })
  const traceNavigation = detail.getByRole('navigation', { name: 'Trace span navigation' })
  const tracePosition = traceNavigation.locator('output')
  const payloadBottomGap = () => detail.evaluate((element) => {
    const payload = element.querySelector('.traffic-payload, .traffic-semantic-card')
    if (!(payload instanceof HTMLElement)) return null
    return Math.round(element.getBoundingClientRect().bottom - payload.getBoundingClientRect().bottom)
  })

  await selectFirstTraceSpan(traceNavigation)
  const initialPayloadBottomGap = await payloadBottomGap()
  expect(initialPayloadBottomGap).toBeGreaterThanOrEqual(15)
  expect(initialPayloadBottomGap).toBeLessThanOrEqual(18)

  await page.keyboard.press('ArrowRight')
  await expect(tracePosition).toHaveAttribute('aria-label', /Span 2 of \d+/)
  expect(await payloadBottomGap()).toBe(initialPayloadBottomGap)

  await page.keyboard.press('ArrowLeft')
  await expect(tracePosition).toHaveAttribute('aria-label', /Span 1 of \d+/)
  await detail.getByRole('button', { name: 'Full screen traffic details' }).click()
  const overview = detail.getByRole('region', { name: 'Exchange overview' })
  await expect(overview.locator('.traffic-overview__heading')).toHaveText('OVERVIEW')
  await expect(overview).toContainText('ENVIRONMENT')
  await expect(overview).toContainText('TARGET BINDING')
  const compareTab = detail.getByRole('tab', { name: 'COMPARE' })
  await detail.getByRole('tab', { name: 'REQUEST', exact: true }).click()
  await compareTab.click()
  await expect(compareTab).toHaveAttribute('aria-selected', 'true')

  await page.keyboard.press('ArrowRight')
  await expect(tracePosition).toHaveAttribute('aria-label', /Span 2 of \d+/)
  await expect(detail).toHaveClass(/traffic-detail--maximized/)
  await expect(overview).toBeVisible()
  await expect(compareTab).toHaveAttribute('aria-selected', 'true')
  await expect(detail.locator('.traffic-message-workbench--request')).toBeVisible()
  await expect(detail.locator('.traffic-message-workbench--response')).toBeVisible()

  await page.keyboard.press('ArrowLeft')
  await expect(tracePosition).toHaveAttribute('aria-label', /Span 1 of \d+/)
  await expect(detail).toHaveClass(/traffic-detail--maximized/)
  await expect(overview).toBeVisible()
  await expect(compareTab).toHaveAttribute('aria-selected', 'true')
})

test('preserves maximized compare mode while paging through exchanges', async ({ page }) => {
  await authenticate(page, environmentPath('traffic'))
  const marker = `/exchange-drawer-state-${Date.now()}`
  expect((await applicationRequest(`${marker}-first`)).status).toBe(404)
  expect((await applicationRequest(`${marker}-second`)).status).toBe(404)

  const filter = page.getByPlaceholder('filter path, service, edge, status…')
  await filter.fill(marker)
  await page.getByRole('tab', { name: 'EXCHANGES' }).click()
  const rows = page.locator('button.traffic-row').filter({ hasText: marker })
  await expect(rows).toHaveCount(2)
  await rows.first().click()

  const detail = page.getByRole('dialog', { name: /Traffic request and response/ })
  const navigation = detail.getByRole('navigation', { name: 'Exchange navigation' })
  const position = navigation.locator('output')
  await expect(position).toHaveAttribute('aria-label', 'Exchange 1 of 2')
  await detail.getByRole('button', { name: 'Full screen traffic details' }).click()
  const compareTab = detail.getByRole('tab', { name: 'COMPARE' })
  await expect(detail).toHaveClass(/traffic-detail--maximized/)
  await expect(compareTab).toHaveAttribute('aria-selected', 'true')

  await page.keyboard.press('ArrowRight')
  await expect(position).toHaveAttribute('aria-label', 'Exchange 2 of 2')
  await expect(detail).toHaveClass(/traffic-detail--maximized/)
  await expect(compareTab).toHaveAttribute('aria-selected', 'true')

  await page.keyboard.press('ArrowLeft')
  await expect(position).toHaveAttribute('aria-label', 'Exchange 1 of 2')
  await expect(detail).toHaveClass(/traffic-detail--maximized/)
  await expect(compareTab).toHaveAttribute('aria-selected', 'true')
})

test('resets trace navigation to the first span when changing scope', async ({ page }) => {
  await authenticate(page, environmentPath('traffic'))
  const response = await applicationRequest(`/checkout?sku=coffee-mug&quantity=1&scope=${Date.now()}`)
  expect(response.status).toBe(200)

  const row = page.locator('button.trace-row').filter({ hasText: '/checkout' }).first()
  await expect(row).toBeVisible()
  await row.click()
  const waterfall = page.getByRole('region', { name: 'Trace waterfall' })
  await waterfall.getByRole('button', { name: /Inspect external to checkout GET \/checkout/ }).click()

  const detail = page.getByRole('dialog', { name: /Traffic request and response/ })
  const navigation = detail.getByRole('navigation', { name: 'Trace span navigation' })
  const httpScope = navigation.getByRole('button', { name: 'HTTP' })
  const allScope = navigation.getByRole('button', { name: 'ALL' })
  const position = navigation.locator('output')
  await expect(httpScope).toHaveAttribute('aria-pressed', 'true')
  await selectFirstTraceSpan(navigation)
  await navigation.getByRole('button', { name: 'Next visible span in trace' }).click()
  await expect(position).toHaveAttribute('aria-label', /Span 2 of \d+/)

  await allScope.click()
  await expect(allScope).toHaveAttribute('aria-pressed', 'true')
  await expect(position).toHaveAttribute('aria-label', /Span 1 of \d+/)

  await httpScope.click()
  await expect(httpScope).toHaveAttribute('aria-pressed', 'true')
  await expect(position).toHaveAttribute('aria-label', /Span 1 of \d+/)
})
