spring.application.name=inventory
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/portless}
server.shutdown=graceful
management.endpoints.web.exposure.include=health,info
